// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zJBVLGAnHn56dG69ZfdzJzUtgaEBAGw',
    appId: '1:425674823924:web:8203fed82b6defaea9e6a1',
    messagingSenderId: '425674823924',
    projectId: 'jrstore-c2de6',
    authDomain: 'jrstore-c2de6.firebaseapp.com',
    storageBucket: 'jrstore-c2de6.firebasestorage.app',
    measurementId: 'G-WN4CZLRRWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAziUGgQcd1KbmUPeTkIf9Re1wkp1uNQ1Q',
    appId: '1:425674823924:android:3be4d583bea70152a9e6a1',
    messagingSenderId: '425674823924',
    projectId: 'jrstore-c2de6',
    storageBucket: 'jrstore-c2de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcI5J_dYt76Hwk-K0dqKCMp6_X0Wst0Rs',
    appId: '1:425674823924:ios:0a771a37ae5ac0e0a9e6a1',
    messagingSenderId: '425674823924',
    projectId: 'jrstore-c2de6',
    storageBucket: 'jrstore-c2de6.firebasestorage.app',
    iosBundleId: 'com.example.jrStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcI5J_dYt76Hwk-K0dqKCMp6_X0Wst0Rs',
    appId: '1:425674823924:ios:0a771a37ae5ac0e0a9e6a1',
    messagingSenderId: '425674823924',
    projectId: 'jrstore-c2de6',
    storageBucket: 'jrstore-c2de6.firebasestorage.app',
    iosBundleId: 'com.example.jrStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5zJBVLGAnHn56dG69ZfdzJzUtgaEBAGw',
    appId: '1:425674823924:web:7e3fa647e2f9bce9a9e6a1',
    messagingSenderId: '425674823924',
    projectId: 'jrstore-c2de6',
    authDomain: 'jrstore-c2de6.firebaseapp.com',
    storageBucket: 'jrstore-c2de6.firebasestorage.app',
    measurementId: 'G-Z22J9BM48V',
  );
}
